// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import React from "react";
import { Providers } from "./providers"; // Wraps Redux, MUI, and Theme
import { AppBar } from "@/components/core/layout/AppBar";
import { NavigationRail } from "@/components/core/layout/NavigationRail";
import { BottomNavigationBar } from "@/components/core/layout/BottomNavigationBar";
import "./globals.css";

/**
 * Nightingale Root Layout
 * Orchestrates the responsive shell:
 * - Mobile: AppBar + BottomNavigationBar
 * - Tablet/Desktop: NavigationRail + AppBar + Main Content
 */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background antialiased font-sans text-text-high">
        <Providers>
          <div className="flex min-h-screen">
            {/* Desktop/Tablet Sidebar Navigation */}
            <NavigationRail />

            <div className="flex flex-col flex-1 min-w-0">
              {/* Contextual Global Header */}
              <AppBar title="Nightingale" />

              {/* Main Clinical Workspace */}
              <main className="flex-1 overflow-y-auto px-md pt-md pb-[100px] md:pb-md transition-all duration-300">
                <div className="max-w-7xl mx-auto w-full">{children}</div>
              </main>

              {/* Mobile Navigation Anchor */}
              <BottomNavigationBar />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
